# Assignment 1 - All About torch.Tensor

PyTorch is an open-source machine learning library widely used for developing deep learning models. It provides a flexible and efficient framework for building and training neural networks. PyTorch is known for its dynamic computational graph, which enables developers to define and modify models on the fly during runtime, making it a popular choice among researchers and practitioners.

below are some example functions of PyTorch.

- torch.arange
- torch.zeros
- torch.randn
- torch.cat
- torch.transpose

Before we begin, let's install and import PyTorch

In [5]:
# Import torch and other required modules
import torch

## Function 1 - torch.arange

The torch.arange function returns a 1D tensor with values from start to end-1 with a specified step size.

In [6]:
#Example 1 - Working 
arrange = torch.arange(0, 10, 2)
arrange

tensor([0, 2, 4, 6, 8])

In this example, a 1D tensor is created using the torch.arange function. The start value is 0, the end value is 10, and the step size is 2. The resulting tensor will contain the values [0, 2, 4, 6, 8].

In [7]:
#Example 2 - Working
arrange = torch.arange(5)
arrange


tensor([0, 1, 2, 3, 4])

In this example, a 1D tensor is created using the torch.arange function. The start value is 5, the end value is 0, and the step size is -1. The resulting tensor will contain the values [5, 4, 3, 2, 1].



In [8]:
#Example 2 - Breaking
arrange = torch.arange(5, 0, 0)
arrange

RuntimeError: step must be nonzero

This example attempts to create a 1D tensor using torch.arange, but the step argument is set to 0. This is invalid because the step value should be non-zero to determine the interval between values. The function raises a ValueError with the message "step must be non-zero".

## Function 2 - torch.zeros

torch.zeros creates a tensor of specified shape filled with zeros. It is commonly used to initialize tensors before populating them with actual data.

In [9]:
#Example 1 - Working
torch.zeros(2, 3)


tensor([[0., 0., 0.],
        [0., 0., 0.]])

This example showcases the creation of a 2D tensor filled with zeros using torch.zeros. The shape is specified as (2, 3), indicating 2 rows and 3 columns.

In [10]:
#Example 2 - Working
torch.zeros(4)


tensor([0., 0., 0., 0.])

In this example, a 1D tensor of length 4 is created using torch.zeros. Only a single argument of 4 is provided, representing the length of the tensor.

In [11]:
#Example 3 - Breaking
torch.zeros(-1, 3)


RuntimeError: Trying to create tensor with negative dimension -1: [-1, 3]

This example attempts to create a 2D tensor using torch.zeros, but the first dimension is set to -1. This is invalid because tensor dimensions must have non-negative sizes. The function raises a ValueError with the message "Shape dimensions must be non-negative integers".

## Function 3 - torch.randn

torch.randn generates a tensor of specified shape filled with random numbers drawn from a standard normal distribution (mean 0, standard deviation 1). It is often used for initializing weights in neural networks or generating random inputs for testing.

In [12]:
#Example 1 - Working
torch.randn(2, 3)


tensor([[ 0.2061, -1.7754,  0.0324],
        [ 2.2869,  0.7249,  1.0693]])

This example demonstrates the creation of a 2D tensor filled with random numbers from a standard normal distribution using torch.randn. The shape is specified as (2, 3), indicating 2 rows and 3 columns.

In [13]:
#Example 2 - Working
torch.randn(4)


tensor([-1.3797, -1.6756, -0.8536,  1.0595])

In this example, a 1D tensor of length 4 is created using torch.randn. Only a single argument of 4 is provided, representing the length of the tensor.

In [14]:
#Example 3 - Breaking
torch.randn(3, -2)


RuntimeError: Trying to create tensor with negative dimension -2: [3, -2]

This example attempts to create a 2D tensor using torch.randn, but the second dimension is set to -2. This is invalid because tensor dimensions must have non-negative sizes. The function raises a ValueError with the message "Shape dimensions must be non-negative integers".

## Function 4 - torch.cat

torch.cat concatenates tensors along a specified dimension. It allows for combining tensors horizontally or vertically to create a larger tensor.

In [15]:
#Example 1 - Working
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
torch.cat((tensor1, tensor2), dim=0)


tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

This example demonstrates the concatenation of two 2D tensors, tensor1 and tensor2, along dim=0 using torch.cat. The resulting tensor will have a shape of (4, 2) and contain the values from both tensors vertically stacked.

In [16]:
#Example 2 - Working
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
torch.cat((tensor1, tensor2), dim=1)


tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In this example, the same tensors tensor1 and tensor2 are concatenated along dim=1 using torch.cat. The resulting tensor will have a shape of (2, 4) and contain the values from both tensors horizontally concatenated.

In [17]:
#Example 3 - Breaking
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6, 7], [8, 9, 10]])
torch.cat((tensor1, tensor2), dim=0)


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 2 but got size 3 for tensor number 1 in the list.

In this example, the tensors tensor1 and tensor2 are attempted to be concatenated along dim=0 using torch.cat. However, the number of columns in tensor1 and tensor2 is not the same. tensor1 has 2 columns, and tensor2 has 3 columns. This will result in an error since tensors must have the same size along the specified dimension for concatenation. The function will raise a RuntimeError with the message "Sizes of tensors must match in each dimension".

## Function 5 - torch.transpose

The torch.transpose function returns a tensor with the dimensions permuted according to the provided permutation.

In [18]:
#Example 1 - Working
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.transpose(tensor, 0, 1)


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In this example, a 2D tensor tensor is created with shape (2, 3). The torch.transpose function is used to permute the dimensions. The arguments (0, 1) indicate that the first dimension should become the second dimension, and the second dimension should become the first dimension. The resulting tensor will have shape (3, 2) and contain the values [[1, 4], [2, 5], [3, 6]].

In [19]:
#Example 2 - Working
tensor = torch.tensor([1, 2, 3])
torch.transpose(tensor, 0, 0)


tensor([1, 2, 3])

In this example, a 1D tensor tensor is created with shape (3,). The torch.transpose function is used with the same dimension indices (0, 0). Since there is only one dimension, the function will return the original tensor as no permutation is needed.

In [20]:
#Example 3 - Breaking
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.transpose(tensor, 0, 2)


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In this example, a 2D tensor tensor is created with shape (2, 3). The torch.transpose function is used with invalid dimension indices (0, 2). The second dimension index exceeds the maximum number of dimensions in the tensor. This will result in an error, and the function will raise an IndexError with the message "Dimension out of range (expected to be in range of [-2, 1], but got 2)".

## Conclusion

In conclusion, the functions `torch.arange`, `torch.zeros`, `torch.randn`, `torch.cat`, and `torch.transpose` are essential tools in PyTorch for creating, manipulating, and transforming tensors. 

- `torch.arange` is useful for generating sequences of numbers within a specified range, allowing for easy creation of 1D tensors with evenly spaced values.

- `torch.zeros` is commonly used for initializing tensors with a specified shape, filling them with zeros. It is helpful when preparing tensors to store data.

- `torch.randn` generates tensors with random numbers drawn from a standard normal distribution, making it valuable for initializing weights in neural networks or creating random inputs for testing.

- `torch.cat` enables the concatenation of tensors along a specified dimension, providing the ability to combine tensors horizontally or vertically to create larger tensors.

- `torch.transpose` allows for permuting the dimensions of a tensor based on a provided permutation, enabling flexibility in manipulating and processing data with different tensor shapes and orientations.

By leveraging these functions, developers and researchers can perform various operations on tensors, such as creating sequences, initializing tensors, generating random data, combining tensors, and rearranging dimensions. These functions contribute to the versatility and efficiency of PyTorch as a deep learning framework.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://medium.com/swlh/a-beginners-guide-to-pytorch-and-its-most-common-used-functions-c07ef56451d1